# Generated by Django 2.2.25 on 2022-01-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(max_length=2, verbose_name='Месяц')),
                ('year', models.IntegerField(max_length=4, verbose_name='Год')),
                ('cw_kitchen', models.IntegerField(max_length=5, verbose_name='Холодная вода. Кухня.')),
                ('cw_bathroom', models.IntegerField(max_length=5, verbose_name='Холодная вода. Ванная.')),
                ('hw_kitchen', models.IntegerField(max_length=5, verbose_name='Горячая вода. Кухня.')),
                ('hw_bathroom', models.IntegerField(max_length=5, verbose_name='Горячая вода. Ванная.')),
                ('el_1', models.IntegerField(max_length=5, verbose_name='Электричество. Тариф 1 (день).')),
                ('el_2', models.IntegerField(max_length=5, verbose_name='Электричество. Тариф 2 (ночь).')),
                ('date_get', models.DateField(verbose_name='Дата снятия показаний')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Показания счётчиков',
                'verbose_name_plural': 'Показания счётчиков',
                'ordering': ['-date_get'],
            },
        ),
    ]
