# Generated by Django 2.2.25 on 2022-01-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Начало действия тарифов')),
                ('water_supply', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Водоснабжение и водоотведение')),
                ('cold_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Холодная вода')),
                ('hot_water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Горячая вода')),
                ('el_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Электричество: день')),
                ('el_night', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Электричество: ночь')),
            ],
            options={
                'verbose_name': 'Тарифы',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-date_start'],
            },
        ),
        migrations.AlterField(
            model_name='counters',
            name='cw_bathroom',
            field=models.IntegerField(verbose_name='Холодная вода: Ванная'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='cw_kitchen',
            field=models.IntegerField(verbose_name='Холодная вода: Кухня'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='el_1',
            field=models.IntegerField(verbose_name='Электричество: Тариф 1 (день)'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='el_2',
            field=models.IntegerField(verbose_name='Электричество: Тариф 2 (ночь)'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='hw_bathroom',
            field=models.IntegerField(verbose_name='Горячая вода: Ванная'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='hw_kitchen',
            field=models.IntegerField(verbose_name='Горячая вода: Кухня'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='month',
            field=models.IntegerField(verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='counters',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
