# Generated by Django 2.2.25 on 2022-01-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_auto_20220115_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffs',
            name='water_drainage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Водоотведение'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='water_supply',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Водоснабжение'),
        ),
    ]
