# Generated by Django 2.2.25 on 2022-01-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_auto_20220115_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffs',
            name='cold_water',
        ),
        migrations.RemoveField(
            model_name='tariffs',
            name='hot_water',
        ),
        migrations.AddField(
            model_name='tariffs',
            name='heating_water',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Подогрев воды'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='el_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Электричество: день'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='el_night',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Электричество: ночь'),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='water_supply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Водоснабжение'),
        ),
    ]
