# Generated by Django 2.2.25 on 2022-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0004_auto_20220115_1822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counters',
            options={'get_latest_by': ['-year', '-month'], 'ordering': ['-year', '-month'], 'verbose_name': 'Показания счётчиков', 'verbose_name_plural': 'Показания счётчиков'},
        ),
        migrations.AddField(
            model_name='counters',
            name='img',
            field=models.ImageField(default=1, upload_to='%Y/%m/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='counters',
            unique_together={('month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='tariffs',
            unique_together={('date_start',)},
        ),
    ]
