# Generated by Django 2.2.25 on 2022-01-24 14:19

from django.db import migrations, models
import prospect.utils


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0005_auto_20220124_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='img',
        ),
        migrations.AddField(
            model_name='counters',
            name='image',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
