# Generated by Django 2.2.25 on 2022-01-25 14:17

from django.db import migrations, models
import prospect.utils


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0006_auto_20220124_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counters',
            name='image',
        ),
        migrations.AddField(
            model_name='counters',
            name='cw_bathroom_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='counters',
            name='cw_kitchen_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='counters',
            name='el_1_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='counters',
            name='el_2_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='counters',
            name='hw_bathroom_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='counters',
            name='hw_kitchen_img',
            field=models.ImageField(blank=True, upload_to=prospect.utils.get_timestamp_path, verbose_name='Фото'),
        ),
    ]
